### ISSUE TITLE
Cannot open precompiled header file

### ISSUE THREAD

**Issue by JayneFrack** [alxbrn/r6s-internal#1]
When I try to build I keep getting this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open precompiled header file: 'Release\Project Frost.pch': No such file or directory	Project Frost	c:\users\Admin\onedrive\desktop\r6-internal-cheat-master\hooks.cpp	1	

what can I do?

**Comment by NmLa0s** [comment]
learn cpp

**Comment by alxbrn** [comment]
You need to build the project as x64 release, and it would be a smart idea to learn basic c++ before jumping into a larger project.
